package br.com.grvivian.view;

import br.com.grvivian.hibernate.ConfigDB;
import br.com.grvivian.hibernate.HibernateDataModel;
import br.com.grvivian.hibernate.HibernateUtil;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.text.DecimalFormat;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;
import org.apache.mahout.cf.taste.common.TasteException;
import org.apache.mahout.cf.taste.eval.IRStatistics;
import org.apache.mahout.cf.taste.eval.RecommenderBuilder;
import org.apache.mahout.cf.taste.eval.RecommenderEvaluator;
import org.apache.mahout.cf.taste.eval.RecommenderIRStatsEvaluator;
import org.apache.mahout.cf.taste.impl.eval.AverageAbsoluteDifferenceRecommenderEvaluator;
import org.apache.mahout.cf.taste.impl.eval.GenericRecommenderIRStatsEvaluator;
import org.apache.mahout.cf.taste.impl.eval.RMSRecommenderEvaluator;
import org.apache.mahout.cf.taste.impl.model.GenericBooleanPrefDataModel;
import org.apache.mahout.cf.taste.impl.model.GenericPreference;
import org.apache.mahout.cf.taste.impl.model.file.FileDataModel;
import org.apache.mahout.cf.taste.impl.neighborhood.NearestNUserNeighborhood;
import org.apache.mahout.cf.taste.impl.neighborhood.ThresholdUserNeighborhood;
import org.apache.mahout.cf.taste.impl.recommender.GenericItemBasedRecommender;
import org.apache.mahout.cf.taste.impl.recommender.GenericUserBasedRecommender;
import org.apache.mahout.cf.taste.impl.similarity.CityBlockSimilarity;
import org.apache.mahout.cf.taste.impl.similarity.EuclideanDistanceSimilarity;
import org.apache.mahout.cf.taste.impl.similarity.LogLikelihoodSimilarity;
import org.apache.mahout.cf.taste.impl.similarity.PearsonCorrelationSimilarity;
import org.apache.mahout.cf.taste.impl.similarity.SpearmanCorrelationSimilarity;
import org.apache.mahout.cf.taste.impl.similarity.TanimotoCoefficientSimilarity;
import org.apache.mahout.cf.taste.impl.similarity.UncenteredCosineSimilarity;
import org.apache.mahout.cf.taste.model.DataModel;
import org.apache.mahout.cf.taste.model.JDBCDataModel;
import org.apache.mahout.cf.taste.neighborhood.UserNeighborhood;
import org.apache.mahout.cf.taste.recommender.RecommendedItem;
import org.apache.mahout.cf.taste.recommender.Recommender;
import org.apache.mahout.cf.taste.similarity.ItemSimilarity;
import org.apache.mahout.cf.taste.similarity.UserSimilarity;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.query.NativeQuery;

/**
 *
 * @author glaucio
 */
public class FrmMain extends javax.swing.JFrame {

  private static final DecimalFormat DF = new DecimalFormat("#0.0000");
  private final ConfigDB configDB = new ConfigDB();
  private final FrmDB frmBD = new FrmDB(configDB);
  private final RecommenderIRStatsEvaluator irStats = new GenericRecommenderIRStatsEvaluator();
  private final RecommenderEvaluator rms = new RMSRecommenderEvaluator();
  private final RecommenderEvaluator mae = new AverageAbsoluteDifferenceRecommenderEvaluator();

  /**
   * Creates new form FrmMain
   */
  public FrmMain() {
    initComponents();

    cbModel.removeAllItems();
    //cbModel.addItem(JDBCDataModel.class.getSimpleName());
    cbModel.addItem(FileDataModel.class.getSimpleName());
    //cbModel.addItem(GenericPreference.class.getSimpleName());
    //cbModel.addItem(GenericBooleanPrefDataModel.class.getSimpleName());
    cbModel.addItem(HibernateDataModel.class.getSimpleName());

    cbNN.removeAllItems();
    cbNN.addItem(NearestNUserNeighborhood.class.getSimpleName());
    cbNN.addItem(ThresholdUserNeighborhood.class.getSimpleName());

    rbItemBased.setSelected(true);
  }

  private final HashSet<Long> userIds = new HashSet<>();

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    btRun = new javax.swing.JButton();
    rbUserBased = new javax.swing.JRadioButton();
    rbItemBased = new javax.swing.JRadioButton();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jLayeredPane1 = new javax.swing.JLayeredPane();
    jLabel1 = new javax.swing.JLabel();
    cbModel = new javax.swing.JComboBox();
    jLabel4 = new javax.swing.JLabel();
    btFindFile = new javax.swing.JButton();
    tfModelFile = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    tbPreferences = new javax.swing.JTable();
    jLayeredPane2 = new javax.swing.JLayeredPane();
    cbNN = new javax.swing.JComboBox();
    cbSimilarity = new javax.swing.JComboBox();
    lbNN = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lbNumOfUsers = new javax.swing.JLabel();
    lbThreshold = new javax.swing.JLabel();
    slThreshold = new javax.swing.JSlider();
    spNumOfUser = new javax.swing.JSpinner();
    jPanel1 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    slNumOfRecomendations = new javax.swing.JSlider();
    jLabel3 = new javax.swing.JLabel();
    cbRecommendationsToUser = new javax.swing.JComboBox<>();
    jLayeredPane3 = new javax.swing.JLayeredPane();
    jScrollPane2 = new javax.swing.JScrollPane();
    taOutput = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("MahoutGUI");

    btRun.setText("Run");
    btRun.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btRunActionPerformed(evt);
      }
    });

    buttonGroup1.add(rbUserBased);
    rbUserBased.setText("User-Based");
    rbUserBased.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    rbUserBased.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        rbUserBasedItemStateChanged(evt);
      }
    });

    buttonGroup1.add(rbItemBased);
    rbItemBased.setText("Item-Based");
    rbItemBased.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        rbItemBasedItemStateChanged(evt);
      }
    });

    jLabel1.setLabelFor(cbModel);
    jLabel1.setText("Model:");

    cbModel.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cbModelItemStateChanged(evt);
      }
    });

    jLabel4.setLabelFor(tfModelFile);
    jLabel4.setText("File:");

    btFindFile.setText("...");
    btFindFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btFindFileActionPerformed(evt);
      }
    });

    tbPreferences.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "User ID", "Item ID", "Preference"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Long.class, java.lang.Long.class, java.lang.Double.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tbPreferences);
    if (tbPreferences.getColumnModel().getColumnCount() > 0) {
      tbPreferences.getColumnModel().getColumn(0).setResizable(false);
      tbPreferences.getColumnModel().getColumn(1).setResizable(false);
      tbPreferences.getColumnModel().getColumn(2).setResizable(false);
    }

    jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(cbModel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(btFindFile, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(tfModelFile, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
    jLayeredPane1.setLayout(jLayeredPane1Layout);
    jLayeredPane1Layout.setHorizontalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel1)
              .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(tfModelFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFindFile))
              .addComponent(cbModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        .addContainerGap())
    );
    jLayeredPane1Layout.setVerticalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(cbModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btFindFile)
          .addComponent(tfModelFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab("Data Model", jLayeredPane1);

    cbNN.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cbNNItemStateChanged(evt);
      }
    });

    lbNN.setLabelFor(cbNN);
    lbNN.setText("Nearest Neighborhood:");

    jLabel2.setLabelFor(cbSimilarity);
    jLabel2.setText("Similarity:");

    lbNumOfUsers.setLabelFor(spNumOfUser);
    lbNumOfUsers.setText("Num. of Users:");
    lbNumOfUsers.setName(""); // NOI18N

    lbThreshold.setLabelFor(slThreshold);
    lbThreshold.setText("Threshold:");

    spNumOfUser.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));
    spNumOfUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generate Recommendations"));

    jLabel5.setText("to User ID:");

    slNumOfRecomendations.setMinimum(1);
    slNumOfRecomendations.setValue(5);

    jLabel3.setText("Quantity:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(31, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(slNumOfRecomendations, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
          .addComponent(cbRecommendationsToUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(cbRecommendationsToUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slNumOfRecomendations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jLabel3)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );

    jLayeredPane2.setLayer(cbNN, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(cbSimilarity, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(lbNN, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(lbNumOfUsers, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(lbThreshold, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(slThreshold, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(spNumOfUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
    jLayeredPane2.setLayout(jLayeredPane2Layout);
    jLayeredPane2Layout.setHorizontalGroup(
      jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane2Layout.createSequentialGroup()
        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jLayeredPane2Layout.createSequentialGroup()
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(lbThreshold)
              .addComponent(lbNumOfUsers)
              .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbNN)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(spNumOfUser)
              .addComponent(cbNN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(cbSimilarity, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(slThreshold, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
          .addGroup(jLayeredPane2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jLayeredPane2Layout.setVerticalGroup(
      jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cbSimilarity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(16, 16, 16)
        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cbNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbNN))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbNumOfUsers)
          .addComponent(spNumOfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(slThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jLayeredPane2Layout.createSequentialGroup()
            .addGap(11, 11, 11)
            .addComponent(lbThreshold)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(31, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Options", jLayeredPane2);

    taOutput.setColumns(20);
    taOutput.setRows(5);
    jScrollPane2.setViewportView(taOutput);

    jLayeredPane3.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
    jLayeredPane3.setLayout(jLayeredPane3Layout);
    jLayeredPane3Layout.setHorizontalGroup(
      jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        .addContainerGap())
    );
    jLayeredPane3Layout.setVerticalGroup(
      jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab("Recommendations Results", jLayeredPane3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(172, 172, 172)
        .addComponent(rbUserBased)
        .addGap(18, 18, 18)
        .addComponent(rbItemBased)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jTabbedPane1)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btRun, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rbUserBased)
          .addComponent(rbItemBased))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jTabbedPane1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btRun)
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void addOutput(String t) {
    taOutput.setText(taOutput.getText() + "\n" + t);
  }

  private void performItemRecommendation(DataModel model, ItemSimilarity itemSimilarity, long userId, int numberOfRecommendation) throws TasteException {
    RecommenderBuilder recommenderBuilder = new RecommenderBuilder() {
      @Override
      public Recommender buildRecommender(DataModel model) throws TasteException {
        return new GenericItemBasedRecommender(model, itemSimilarity);
      }
    };

    //Recommender itemRecommender = new GenericItemBasedRecommender(model, itemSimilarity);
    List<RecommendedItem> itemBasedRecommendations = recommenderBuilder.buildRecommender(model).recommend(userId, numberOfRecommendation);

    int cont = 0;
    addOutput("Items Recommended for user " + userId + ":");
    for (RecommendedItem r : itemBasedRecommendations) {
      addOutput("- " + r.getItemID() + " preference predicted is " + r.getValue());
      cont++;
    }

    IRStatistics stats = irStats.evaluate(recommenderBuilder, null, model, null, cont, GenericRecommenderIRStatsEvaluator.CHOOSE_THRESHOLD, 1.0);

    // Use 70% of the data to train; test using the other 30%.
    double r = rms.evaluate(recommenderBuilder, null, model, 0.7, 1.0);
    double m = mae.evaluate(recommenderBuilder, null, model, 0.7, 1.0);

    addOutput(" Precision: " + DF.format(stats.getPrecision())
            + " Recall: " + DF.format(stats.getRecall())
            + " RMSE: " + DF.format(r)
            + " MAE: " + DF.format(m) + "\n");
  }

  private void performUserRecommendation(DataModel model, UserNeighborhood neighbour, UserSimilarity similarity, long userId, int numberOfRecommendation) throws TasteException {
    RecommenderBuilder recommenderBuilder = new RecommenderBuilder() {
      @Override
      public Recommender buildRecommender(DataModel model) throws TasteException {
        return new GenericUserBasedRecommender(model, neighbour, similarity);
      }
    };

    //Recommender recommender = new GenericUserBasedRecommender(model, neighbour, similarity);
    List<RecommendedItem> recommendations = recommenderBuilder.buildRecommender(model).recommend(userId, numberOfRecommendation);

    int cont = 0;
    addOutput("Items Recommended for user " + userId + ":");
    for (RecommendedItem r : recommendations) {
      addOutput("- " + r.getItemID() + " preference predicted: " + r.getValue());
      cont++;
    }

    IRStatistics stats = irStats.evaluate(recommenderBuilder, null, model, null, cont, GenericRecommenderIRStatsEvaluator.CHOOSE_THRESHOLD, 1.0);

    // Use 70% of the data to train; test using the other 30%.
    double r = rms.evaluate(recommenderBuilder, null, model, 0.7, 1.0);
    double m = mae.evaluate(recommenderBuilder, null, model, 0.7, 1.0);

    addOutput(" Precision: " + DF.format(stats.getPrecision())
            + " Recall: " + DF.format(stats.getRecall())
            + " RMSE: " + DF.format(r)
            + " MAE: " + DF.format(m) + "\n");
  }

  private void setUserDetails() {
    spNumOfUser.setModel(new javax.swing.SpinnerNumberModel(1, 1, userIds.size(), 1));
    cbRecommendationsToUser.removeAllItems();
    Iterator<Long> it = userIds.iterator();
    while (it.hasNext()) {
      Long id = it.next();
      cbRecommendationsToUser.addItem(id);
    }
  }

  private void btRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunActionPerformed
    try {

      //Model
      DataModel model = null;
      if (cbModel.getSelectedItem().equals(JDBCDataModel.class.getSimpleName())) {
        //model = new JDBCDataModel();
      } else if (cbModel.getSelectedItem().equals(FileDataModel.class.getSimpleName())) {
        File f = new File(tfModelFile.getText());
        if (!f.exists()) {
          JOptionPane.showMessageDialog(null, "File Not Found!");
          return;
        }
        model = new FileDataModel(f);
      } else if (cbModel.getSelectedItem().equals(GenericPreference.class.getSimpleName())) {
        //model = new GenericDataModel();
      } else if (cbModel.getSelectedItem().equals(GenericBooleanPrefDataModel.class.getSimpleName())) {

      } else if (cbModel.getSelectedItem().equals(HibernateDataModel.class.getSimpleName())) {
        model = new HibernateDataModel(configDB);
      }

      long userID = (long) cbRecommendationsToUser.getSelectedItem();
      int NumOfRec = slNumOfRecomendations.getValue();

      //Nearest Neighborhood
      UserNeighborhood un = null;
      if (rbItemBased.isSelected()) {
        ItemSimilarity is = null;

        //Similarity       
        if (cbSimilarity.getSelectedItem().equals(LogLikelihoodSimilarity.class.getSimpleName())) {
          is = new LogLikelihoodSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(PearsonCorrelationSimilarity.class.getSimpleName())) {
          is = new PearsonCorrelationSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(SpearmanCorrelationSimilarity.class.getSimpleName())) {
          ///is = new SpearmanCorrelationSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(TanimotoCoefficientSimilarity.class.getSimpleName())) {
          is = new TanimotoCoefficientSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(CityBlockSimilarity.class.getSimpleName())) {
          is = new CityBlockSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(EuclideanDistanceSimilarity.class.getSimpleName())) {
          is = new EuclideanDistanceSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(UncenteredCosineSimilarity.class.getSimpleName())) {
          is = new UncenteredCosineSimilarity(model);
        }

        performItemRecommendation(model, is, userID, NumOfRec);
      } else if (rbUserBased.isSelected()) {
        UserSimilarity us = null;

        //Similarity       
        if (cbSimilarity.getSelectedItem().equals(LogLikelihoodSimilarity.class.getSimpleName())) {
          us = new LogLikelihoodSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(PearsonCorrelationSimilarity.class.getSimpleName())) {
          us = new PearsonCorrelationSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(SpearmanCorrelationSimilarity.class.getSimpleName())) {
          us = new SpearmanCorrelationSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(TanimotoCoefficientSimilarity.class.getSimpleName())) {
          us = new TanimotoCoefficientSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(CityBlockSimilarity.class.getSimpleName())) {
          us = new CityBlockSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(EuclideanDistanceSimilarity.class.getSimpleName())) {
          us = new EuclideanDistanceSimilarity(model);
        } else if (cbSimilarity.getSelectedItem().equals(UncenteredCosineSimilarity.class.getSimpleName())) {
          us = new UncenteredCosineSimilarity(model);
        }

        if (cbNN.getSelectedItem().equals(NearestNUserNeighborhood.class.getSimpleName())) {
          int n = (int) spNumOfUser.getValue();
          un = new NearestNUserNeighborhood(n, us, model);
        } else if (cbNN.getSelectedItem().equals(ThresholdUserNeighborhood.class.getSimpleName())) {
          double t = (double) (slThreshold.getValue() / 100);
          un = new ThresholdUserNeighborhood(t, us, model);
        }

        performUserRecommendation(model, un, us, userID, NumOfRec);
      }
    } catch (Exception ex) {
      Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, ex.getMessage());
    }
  }//GEN-LAST:event_btRunActionPerformed

  private void btFindFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindFileActionPerformed
    try {
      JFileChooser abrir = new JFileChooser();
      abrir.setFileFilter(new FileNameExtensionFilter("CSV File", "csv"));
      int retorno = abrir.showOpenDialog(null);
      if (retorno == JFileChooser.APPROVE_OPTION) {
        tfModelFile.setText(abrir.getSelectedFile().getAbsolutePath());
      }

      userIds.clear();
      String arq = FileUtils.readFileToString(abrir.getSelectedFile(), "UTF-8");
      String[] linha = arq.split("\n");
      String[] coluns = new String[]{"User ID", "Item ID", "Preference"};
      Object[][] data = new Object[linha.length][3];

      for (int i = 0; i < linha.length; i++) {
        String linha1 = linha[i];
        String[] col = linha1.split(",");

        if (col.length != 3) {
          return;
        }

        Long userId = Long.parseLong(col[0]);
        if (!userIds.contains(userId)) {
          userIds.add(userId);
        }

        data[i][0] = userId;
        data[i][1] = Long.parseLong(col[1]);
        data[i][2] = Double.parseDouble(col[2]);
      }

      setUserDetails();
      tbPreferences.setModel(new javax.swing.table.DefaultTableModel(data, coluns) {
        Class[] types = new Class[]{java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class};
        boolean[] canEdit = new boolean[]{false, false, false};

        @Override
        public Class getColumnClass(int columnIndex) {
          return types[columnIndex];
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
          return canEdit[columnIndex];
        }
      });
    } catch (IOException ex) {
      Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, ex.getMessage());
    }
  }//GEN-LAST:event_btFindFileActionPerformed

  private void cbNNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNNItemStateChanged
    spNumOfUser.setEnabled(false);
    lbNumOfUsers.setEnabled(false);
    slThreshold.setEnabled(false);
    lbThreshold.setEnabled(false);

    if (!cbNN.isEnabled()) {
      return;
    }

    if (cbNN.getSelectedItem().equals(NearestNUserNeighborhood.class.getSimpleName())) {
      spNumOfUser.setEnabled(true);
      lbNumOfUsers.setEnabled(true);
    } else if (cbNN.getSelectedItem().equals(ThresholdUserNeighborhood.class.getSimpleName())) {
      slThreshold.setEnabled(true);
      lbThreshold.setEnabled(true);
    }
  }//GEN-LAST:event_cbNNItemStateChanged

  private void rbUserBasedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbUserBasedItemStateChanged
    if (rbUserBased.isSelected()) {
      cbNN.setEnabled(true);
      lbNN.setEnabled(true);
      cbNNItemStateChanged(evt);

      cbSimilarity.removeAllItems();
      cbSimilarity.addItem(LogLikelihoodSimilarity.class.getSimpleName());
      cbSimilarity.addItem(PearsonCorrelationSimilarity.class.getSimpleName());
      cbSimilarity.addItem(SpearmanCorrelationSimilarity.class.getSimpleName());//Just to Item-based
      cbSimilarity.addItem(TanimotoCoefficientSimilarity.class.getSimpleName());
      cbSimilarity.addItem(CityBlockSimilarity.class.getSimpleName());
      cbSimilarity.addItem(EuclideanDistanceSimilarity.class.getSimpleName());
      cbSimilarity.addItem(UncenteredCosineSimilarity.class.getSimpleName());
    }
  }//GEN-LAST:event_rbUserBasedItemStateChanged

  private void rbItemBasedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbItemBasedItemStateChanged
    if (rbItemBased.isSelected()) {
      cbNN.setEnabled(false);
      lbNN.setEnabled(false);
      cbNNItemStateChanged(evt);

      cbSimilarity.removeAllItems();
      cbSimilarity.addItem(LogLikelihoodSimilarity.class.getSimpleName());
      cbSimilarity.addItem(PearsonCorrelationSimilarity.class.getSimpleName());
      //cbSimilarity.addItem(SpearmanCorrelationSimilarity.class.getSimpleName());//Just to Item-based
      cbSimilarity.addItem(TanimotoCoefficientSimilarity.class.getSimpleName());
      cbSimilarity.addItem(CityBlockSimilarity.class.getSimpleName());
      cbSimilarity.addItem(EuclideanDistanceSimilarity.class.getSimpleName());
      cbSimilarity.addItem(UncenteredCosineSimilarity.class.getSimpleName());
    }
  }//GEN-LAST:event_rbItemBasedItemStateChanged

  private void getDataFromDB() throws Exception {
    userIds.clear();
    String[] coluns = new String[]{"User ID", "Item ID", "Preference"};
    Object[][] data = null;

    Session s = null;
    Transaction t = null;
    List<Object[]> lista = null;

    try {
      s = HibernateUtil.getSessionFactory(this.configDB).openSession();
      t = s.beginTransaction();
      //t.begin();
      NativeQuery q = s.createNativeQuery("select "
              + this.configDB.getUser_id() + " , "//as userId
              + this.configDB.getItem_id() + " , "//as itemId
              + this.configDB.getPref() + "  "//as preference
              + " from " + this.configDB.getTable() + "  "//as Preferences
              + " order by 1"); //Important
      lista = q.setCacheable(true).list();

      data = new Object[lista.size()][3];

      for (int x = 0; x < lista.size(); x++) {
        Object[] o = lista.get(x);

        if (o.length != 3) {
          return;
        }

        BigInteger u = (BigInteger) o[0];
        BigInteger i = (BigInteger) o[1];
        float pref = (float) o[2];

        Long userId = u.longValue();
        if (!userIds.contains(userId)) {
          userIds.add(userId);
        }

        data[x][0] = u.longValue();
        data[x][1] = i.longValue();
        data[x][2] = pref;
      }

      t.commit();
    } catch (HibernateException e) {
      if ((t != null) && (t.isActive())) {
        t.rollback();
      }
      throw e;
    } finally {
      if ((s != null) && (s.isConnected())) {
        s.close();
      }
    }

    setUserDetails();
    tbPreferences.setModel(new javax.swing.table.DefaultTableModel(data, coluns) {
      Class[] types = new Class[]{java.lang.Long.class, java.lang.Long.class, java.lang.Float.class};
      boolean[] canEdit = new boolean[]{false, false, false};

      @Override
      public Class getColumnClass(int columnIndex) {
        return types[columnIndex];
      }

      @Override
      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit[columnIndex];
      }
    });
  }

  private void cbModelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbModelItemStateChanged
    try {
      if (cbModel.getSelectedItem().equals(FileDataModel.class.getSimpleName())) {

      } else if (cbModel.getSelectedItem().equals(HibernateDataModel.class.getSimpleName())) {
        frmBD.setVisible(true);
        getDataFromDB();
        setUserDetails();
      }
    } catch (Exception ex) {
      Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_cbModelItemStateChanged

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
        if ("GTK+".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      JOptionPane.showMessageDialog(null, ex.getMessage());
      Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new FrmMain().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btFindFile;
  private javax.swing.JButton btRun;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JComboBox cbModel;
  private javax.swing.JComboBox cbNN;
  private javax.swing.JComboBox<Long> cbRecommendationsToUser;
  private javax.swing.JComboBox cbSimilarity;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLayeredPane jLayeredPane1;
  private javax.swing.JLayeredPane jLayeredPane2;
  private javax.swing.JLayeredPane jLayeredPane3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JLabel lbNN;
  private javax.swing.JLabel lbNumOfUsers;
  private javax.swing.JLabel lbThreshold;
  private javax.swing.JRadioButton rbItemBased;
  private javax.swing.JRadioButton rbUserBased;
  private javax.swing.JSlider slNumOfRecomendations;
  private javax.swing.JSlider slThreshold;
  private javax.swing.JSpinner spNumOfUser;
  private javax.swing.JTextArea taOutput;
  private javax.swing.JTable tbPreferences;
  private javax.swing.JTextField tfModelFile;
  // End of variables declaration//GEN-END:variables
}
